version: '3.8'

services:
  finance-report:
    image: ghcr.io/exploitacious/finance-report:latest
    container_name: finance-report
    ports:
      - "3020:8000"
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - ivantsov-tech_default

networks:
  ivantsov-tech_default:
    external: true
